MODEL_LIST =   [
            {
                "id": "flux",
                "name": "FLUX Transformer",
                "description": "A 12B rectified flow transformer model for high-fidelity image generation.",
                "icon_url": "flux.png",
                "available": True,
                "trigger_word": None,
                "tags": ["high-quality", "experimental"],
                "image_data": None,
            },
            {
                "id": "sd3.5",
                "name": "Stable Diffusion 3.5",
                "description": "A cutting-edge text-to-image model from Stability AI. Delivers improved coherence, detail, and image fidelity over previous SD versions. Great for both photorealistic and artistic generations.",
                "icon_url": "stable-diffusion.png",
                "available": True,
                "trigger_word": None,
                "tags": ["stable", "photorealistic", "balanced", "v3"],
                "image_data": None,
            },
            {
                "id": "opendalle",
                "name": "Open Dalle v1.1",
                "description": "A cutting-edge text-to-image model from that competes with DALLE-3.",
                "icon_url": "open-dalle.png",
                "available": True,
                "trigger_word": None,
                "tags": ["stable", "photorealistic", "balanced", "v3"],
                "image_data": None,
            },
            {
                "id": "sdxl-turbo",
                "name": "SDXL-Turbo",
                "description": "SDXL-Turbo is a fast generative text-to-image model that can synthesize photorealistic images from a text prompt in a single network evaluation.",
                "icon_url": "sdxl-turbo.png",
                "available": True,
                "trigger_word": None,
                "tags": ["turbo", "photorealistic", "balanced"],
                "image_data": None,
            },
            {
                "id": "ghibli",
                "name": "Flux Anime Ghibli Art LoRA",
                "description": "A Flux LoRa in the style of Anime Ghibli Art.",
                "icon_url": "ghibli.png",
                "trigger_word": "Ghibli Art",
                "available": True,
                "tags": ["LoRA", "artistic", "ghibli-style"],
                "image_data": None,
            },
            {
                "id": "flux-aestehticanime",
                "name": "Flux Aesthetic Anime LoRA",
                "description": "A Flux LoRa in the style and aesthetic of ghibli retro anime.",
                "icon_url": "flux-aesthetic-anime.png",
                "trigger_word": None,
                "available": True,
                "tags": ["LoRA", "artistic", "ghibli-style"],
                "image_data": None,
            },
            {
                "id": "iso",
                "name": "Flux Isometric 3D LoRA",
                "description": "A Flux LoRA in the style of isometric 3D.",
                "icon_url": "iso.png",
                "trigger_word": "Isometric 3D",
                "available": True,
                "tags": ["LoRA", "artistic", "iso-style"],
                "image_data": None,
            },
            {
                "id": "super-realism",
                "name": "Flux Super Realism LoRA",
                "description": "A Flux LoRA for super realism.",
                "icon_url": "super-realisim.png",
                "trigger_word": "Super Realism",
                "available": True,
                "tags": ["LoRA", "super-realism", "artistic"],
                "image_data": None,
            },
            {
                "id": "sdxl-base",
                "name": "SD-XL 1.0 Base ",
                "description": "generative text-to-image model that can synthesize photorealistic images from a text prompt",
                "icon_url": "flux.png",
                "trigger_word": None,
                "available": False,
                "tags": ["SD-XL", "high-quality", "balanced"],
                "image_data": None,
            }                                                         


            # Add more as needed...
        ]  
